# Pandas Data Cleaning

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

# Load data
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset["train"].to_pandas()

# Data cleanup
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

c:\Users\PC\anaconda3\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df.loc[:10, "salary_year_avg":"salary_hour_avg"]

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

## Filling na values

In [3]:
median_salary_year = df["salary_year_avg"].median()
median_salary_year

115000.0

In [4]:
median_salary_hour = df["salary_hour_avg"].median()
median_salary_hour

45.97999954223633

In [5]:
df_filled = df

df_filled["salary_year_avg"] = df_filled["salary_year_avg"].fillna(median_salary_year)
df_filled["salary_hour_avg"] = df_filled["salary_hour_avg"].fillna(median_salary_hour)

In [6]:
df.loc[:10, "salary_year_avg":"salary_hour_avg"]

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

## Dropping duplicates

In [7]:
df_unique = df_filled

df_unique = df_unique.drop_duplicates()

print("Length of original df:               ", len(df_filled))
print("Length of drop duplicates df:        ", len(df_unique))
print("Rows dropped:                        ", len(df_filled) - len(df_unique))

Length of original df:                785741
Length of drop duplicates df:         785640
Rows dropped:                         101

In [8]:
# Dropping repetitive jobs
df_unique = df_unique.drop_duplicates(subset=["job_title", "company_name"])

print("Length of original df:               ", len(df_filled))
print("Length of drop duplicates df:        ", len(df_unique))
print("Rows dropped:                        ", len(df_filled) - len(df_unique))

Length of original df:                785741
Length of drop duplicates df:         508042
Rows dropped:                         277699