# Pandas Applying Functions

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

# Load data
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset["train"].to_pandas()
df_sample = dataset["train"].to_pandas()

# Data cleanup
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])
df_sample["job_posted_date"] = pd.to_datetime(df_sample["job_posted_date"])

c:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df["salary_year_avg"]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
785736   NaN
785737   NaN
785738   NaN
785739   NaN
785740   NaN
Name: salary_year_avg, Length: 785741, dtype: float64

In [3]:
df[pd.notna(df["salary_year_avg"])]["salary_year_avg"]

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

## Column apply()

In [4]:
# Calculate project salary next year
df_salary = df[pd.notna(df["salary_year_avg"])].copy()

def projected_salary(salary):
    return salary * 1.03

df_salary["salary_year_inflated"] = df_salary["salary_year_avg"].apply(projected_salary)
df_salary[["salary_year_avg", "salary_year_inflated"]]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [5]:
# Using lambda
df_salary_v2 = df[pd.notna(df["salary_year_avg"])].copy()

df_salary_v2["salary_year_inflated"] = df_salary_v2["salary_year_avg"].apply(lambda salary: salary * 1.03)
df_salary_v2[["salary_year_avg", "salary_year_inflated"]]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [6]:
# Without apply
df_salary_v3 = df[pd.notna(df["salary_year_avg"])].copy()

df_salary_v3["salary_year_inflated"] = df_salary_v3["salary_year_avg"] * 1.03
df_salary_v3[["salary_year_avg", "salary_year_inflated"]]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [7]:
df["job_skills"][1]

"['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']"

In [8]:
type(df["job_skills"][1])

str

In [9]:
list(df["job_skills"][1])

['[',
 "'",
 'r',
 "'",
 ',',
 ' ',
 "'",
 'p',
 'y',
 't',
 'h',
 'o',
 'n',
 "'",
 ',',
 ' ',
 "'",
 's',
 'q',
 'l',
 "'",
 ',',
 ' ',
 "'",
 'n',
 'o',
 's',
 'q',
 'l',
 "'",
 ',',
 ' ',
 "'",
 'p',
 'o',
 'w',
 'e',
 'r',
 ' ',
 'b',
 'i',
 "'",
 ',',
 ' ',
 "'",
 't',
 'a',
 'b',
 'l',
 'e',
 'a',
 'u',
 "'",
 ']']

## Converting a list of strings into a list

In [10]:
import ast

ast.literal_eval(df["job_skills"][1])

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [11]:
type(ast.literal_eval(df["job_skills"][1]))

list

In [12]:
def clean_list(skill_list):
    # Exclude None values
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)

df["job_skills"] = df["job_skills"].apply(clean_list)
df["job_skills"]

0                                                      None
1                [r, python, sql, nosql, power bi, tableau]
2         [python, sql, c#, azure, airflow, dax, docker,...
3         [python, c++, java, matlab, aws, tensorflow, k...
4         [bash, python, oracle, aws, ansible, puppet, j...
                                ...
785736    [bash, python, perl, linux, unix, kubernetes, ...
785737                               [sas, sas, sql, excel]
785738                                  [powerpoint, excel]
785739    [python, go, nosql, sql, mongo, shell, mysql, ...
785740                                          [aws, flow]
Name: job_skills, Length: 785741, dtype: object

In [13]:
type(df["job_skills"][1])

list

### Using lambda

In [14]:
df_sample["job_skills"][1]

"['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']"

In [15]:
type(df_sample["job_skills"][1])

str

In [16]:
df_sample["job_skills"] = df_sample["job_skills"].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else skill_list)
df_sample["job_skills"][1]

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [17]:
type(df["job_skills"][1])

list

## Row apply()

### Calculate projected salary next year

- Senior roles assume 5%
- Other roles assume 3%

In [18]:
# This one applies to the specified column
df_salary["salary_year_inflated"] = df_salary["salary_year_avg"].apply(lambda salary: salary * 1.03)

In [19]:
# This one applies to each row of the specified dataframe
def projected_salary(row):
    if "Senior" in row["job_title_short"]:
        return row["salary_year_avg"] * 1.05
    else:
        return row["salary_year_avg"] * 1.03


df_salary["salary_year_inflated"] = df_salary.apply(projected_salary, axis=1)
df_salary[["job_title_short", "salary_year_avg", "salary_year_inflated"]]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]

### Row apply() with lambda

In [20]:
df_salary_v2 = df_sample[pd.notna(df_sample["salary_year_avg"])].copy()

df_salary_v2["salary_year_inflated"] = (df_salary_v2
                                        .apply(lambda row:  1.05 * row["salary_year_avg"]
                                               if "Senior" in row["job_title_short"]
                                               else 1.03 * row["salary_year_avg"],
                                               axis=1)
                                        )
df_salary_v2[["job_title_short", "salary_year_avg", "salary_year_inflated"]]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]